import { useState, useRef } from 'react'

// ============================================================
// MetabaseDashboard Component (src/components/MetabaseDashboard.jsx)
// --------------------------------------------------------
// A reusable React component that securely embeds a Metabase
// dashboard via an <iframe> using signed (JWT) embedding URLs.
//
// HOW METABASE SECURE EMBEDDING WORKS (REMOTE METABASE):
// ────────────────────────────────────────────────────────────
// 1. The backend (server/index.js) generates a signed JWT token
//    using the METABASE_SECRET_KEY. This token encodes:
//      - resource: { dashboard: DASHBOARD_ID }
//      - params:  any filter parameters to pre-fill
//      - exp:     token expiration timestamp
//
// 2. The backend constructs the full embed URL pointing to
//    the remote Metabase instance:
//      https://metabase.cronous.my.id/embed/dashboard/<token>
//
// 3. This component receives the full iframe URL as a prop and
//    renders it inside an <iframe>. The user's browser loads
//    the dashboard DIRECTLY from metabase.cronous.my.id — our
//    Express backend is NOT a proxy or middleman for the
//    dashboard content.
//
// 4. Metabase validates the JWT signature and serves the
//    dashboard if the token is valid and not expired.
//
// WHY NOT GENERATE THE JWT IN REACT?
// ────────────────────────────────────────────────────────────
// The METABASE_SECRET_KEY must NEVER be exposed in the frontend
// bundle. If we generate the JWT in React, anyone could inspect
// the bundled JavaScript and steal the secret key, allowing
// them to forge tokens and access any dashboard.
// Therefore, JWT generation MUST happen on the backend.
//
// PROPS:
// - iframeUrl: The fully constructed Metabase embedding URL
//              (generated by the backend, e.g.,
//               "https://metabase.cronous.my.id/embed/dashboard/eyJ...")
// - title:     An accessible title for the iframe (used by
//              screen readers to describe the embedded content)
//
// RESPONSIVE DESIGN:
// ────────────────────────────────────────────────────────────
// - The iframe uses w-full h-full to fill its parent container
// - The parent must have a defined height for this to work
// - We set a minimum height of 85vh as a fallback
// - border-0 removes the default iframe border
// ============================================================

export default function MetabaseDashboard({ iframeUrl, title = 'Metabase Dashboard' }) {
  // ----------------------------------------------------------
  // Loading State
  // - The iframe takes a moment to load Metabase's JavaScript
  //   and render the dashboard. We show a loading spinner
  //   until the iframe's onload event fires.
  // - For remote Metabase, this may take slightly longer due
  //   to network latency.
  // ----------------------------------------------------------
  const [isLoading, setIsLoading] = useState(true)
  const iframeRef = useRef(null)

  // ----------------------------------------------------------
  // Iframe Load Handler
  // - Sets isLoading to false once the iframe content finishes
  //   loading. Note: we cannot inspect the iframe content due
  //   to cross-origin restrictions (the iframe is loaded from
  //   metabase.cronous.my.id while our app is on a different
  //   domain), but we can detect when the browser finishes
  //   loading the iframe's src.
  // ----------------------------------------------------------
  const handleIframeLoad = () => {
    setIsLoading(false)
  }

  // ----------------------------------------------------------
  // Error State
  // - If no iframeUrl is provided, we show a helpful error
  //   message instead of a broken iframe.
  // ----------------------------------------------------------
  if (!iframeUrl) {
    return (
      <div className="flex items-center justify-center h-full min-h-[85vh] bg-gray-100 rounded-lg border-2 border-dashed border-gray-300">
        <div className="text-center p-8">
          <svg
            className="w-16 h-16 mx-auto mb-4 text-gray-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={1.5}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
            />
          </svg>
          <h3 className="text-lg font-semibold text-gray-700 mb-2">
            Dashboard URL Tidak Tersedia
          </h3>
          <p className="text-gray-500 max-w-md">
            URL embedding Metabase belum dikonfigurasi. Pastikan backend server
            sudah berjalan dan memberikan URL embedding yang valid.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="relative w-full h-full min-h-[85vh]">
      {/* --------------------------------------------------------
          LOADING SPINNER OVERLAY
          - Positioned absolutely over the iframe
          - Centered spinner with Indonesian text "Memuat..."
          - Hidden once iframe finishes loading (isLoading = false)
          -------------------------------------------------------- */}
      {isLoading && (
        <div className="absolute inset-0 flex items-center justify-center bg-gray-50 z-10 transition-opacity duration-300">
          <div className="text-center">
            {/* Animated spinner */}
            <svg
              className="animate-spin h-10 w-10 text-indigo-600 mx-auto mb-3"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              />
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
              />
            </svg>
            <p className="text-gray-600 font-medium">Memuat Dashboard...</p>
          </div>
        </div>
      )}

      {/* --------------------------------------------------------
          METABASE IFRAME
          - The core element that renders the embedded dashboard
          - key prop forces a full remount when URL changes
          - sandbox attribute restricts the iframe for security:
              • allow-scripts: needed for Metabase JS interactions
              • allow-same-origin: needed for API calls from iframe
              • allow-popups: allows Metabase drill-through to open
            NOTE: We omit allow-forms and allow-top-navigation for
            extra security, preventing unwanted form submissions
            or navigation away from our app.
          - allow attribute grants clipboard permissions for
            Metabase's copy/export features
          - loading="lazy" defers iframe loading until visible
          -------------------------------------------------------- */}
      <iframe
        ref={iframeRef}
        key={iframeUrl}
        src={iframeUrl}
        title={title}
        onLoad={handleIframeLoad}
        className="w-full h-full min-h-[85vh] border-0 rounded-lg"
        sandbox="allow-scripts allow-same-origin allow-popups"
        allow="clipboard-read; clipboard-write"
        loading="lazy"
      />
    </div>
  )
}